name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install Deps
        run: pip install ".[test,dev]"

      - name: Run Pytest
        run: pytest tests/
